### ISSUE TITLE
Come up with design Standard Chasis

### ISSUE THREAD

**Issue by jspspike** [ut-ras/robomaster#1]
- [ ] Use rev bars for frame?
- [ ] Ability to rout/mill panels?
- [ ] Determine wheels
For above we should look at other teams designs to see what's common

**Comment by nickchan23** [comment]
https://docs.google.com/document/d/1O0LMwbcsAn0fGRDV7Skiyf7sXpuNhIhbu9mDnpnFNz8/edit?usp=sharing

**Comment by jspspike** [comment]
https://www.robomaster.com/en-US/resource/pages/announcement/1193
