### ISSUE TITLE
Look at DC Motors

### ISSUE THREAD

**Issue by jspspike** [ut-ras/robomaster#15]
Figure out if we can find a replacement for DJI motors.
We're planning on using [these](https://www.robomaster.com/en-US/products/components/general/M3508) for our base and then possibly [gobuilda motors](https://www.gobilda.com/yellow-jacket-planetary-gear-motors/) for our shooter and gimbal. Try to find similar motors to the DJI one in terms of torque and current draw. They can be either 12v or 24v

**Comment by yuqipan** [comment]
Motor                 Stall Current                    Torque            Notes:
DJI                            2.5A                            4.5Nm           
REV HD Hex              8.5A                           4.2Nm            With the 40:1 gearbox
goBuilda                   9.2A                           3.7Nm            (5202-0002-0027) Currently sold out

Links 
goBuilda: https://www.gobilda.com/5202-series-yellow-jacket-planetary-gear-motor-26-9-1-ratio-223-rpm-3-3-5v-encoder/ 
Rev: https://www.revrobotics.com/rev-41-1301/
