### ISSUE TITLE
Choosing a microcontroller

### ISSUE THREAD

**Issue by jspspike** [ut-ras/robomaster#16]
So we plan to just buy a breakout for the microcontroller at first and this will probably determine which one we will use for the future. Since we can buy [robomaster type c stm32 breakouts](https://www.robomaster.com/en-US/products/components/general/development-board-type-c/info) we are considering those but we _also_ can just buy an stm32/esp32/tm4c/rp2040 breakout with a few voltage regulators and get the same thing. So look at the cost of the type c board and see if it's worth the headache to do the second option or just buy the robomaster ones.

**Comment by alljiang** [comment]
https://rm-static.djicdn.com/tem/35228/RoboMaster%20Development%20Board%20Type%20C%20User%20Manual.pdf
$36 for board
$29 for cables
