### ISSUE TITLE
Come up with design for Standard Shooter

### ISSUE THREAD

**Issue by jspspike** [ut-ras/robomaster#2]
- [ ] Determine flywheel
- [ ] Look at common feeding mechanisms

**Comment by nickchan23** [comment]
https://docs.google.com/document/d/1O0LMwbcsAn0fGRDV7Skiyf7sXpuNhIhbu9mDnpnFNz8/edit?usp=sharing

**Comment by jspspike** [comment]
https://www.robomaster.com/en-US/resource/pages/announcement/1193
