### ISSUE TITLE
Create generic PID motor controller class for simple velocity-based control

### ISSUE THREAD

**Issue by calebchalmers** [ut-ras/robomaster#43]
We have a lot of motors that are velocity-controlled by PIDs and they generally have nearly identical logic. By abstracting this out to a class, it'll clean up our subsystems a lot. We wouldn't need all those PID parameter constants, motor update functions, complicated PID initializations, etc.

**Comment by calebchalmers** [comment]
We need #45 before we can do this effectively.

**Comment by eddieliao** [comment]
Completed
