### ISSUE TITLE
Improve VSCode setup for easy building, debugging, flashing, etc.

### ISSUE THREAD

**Issue by calebchalmers** [ut-ras/robomaster#44]
Currently, we don't have good build tasks, debug targets, etc., and we're typing commands in the terminal manually. It'd be a lot nicer if we setup these things.

**Comment by calebchalmers** [comment]
We need #45 before we can do this effectively.

**Comment by eddieliao** [comment]
tasks.json provides this functionality using VSCode's built in tasks feature. Can also be configured to be bound to specific shortcuts to allow for quick use of certain tasks
