### ISSUE TITLE
Implement Burst Fire

### ISSUE THREAD

**Issue by eddieliao** [ut-ras/robomaster#68]
In theory, we can shoot eight projectiles *very* quickly since that's how many the agitator holds. We need to implement and test this with different fire rates. Firing them too fast may be a waste due to invulnerability time in the armor plates. Maybe there it's still worth having for spray and pray reasons? We need to consider barrel overheat for each level. We can alternate barrels with each burst.

**Comment by calebchalmers** [comment]
Closed with #87
